spring:
  application:
    name: "Estoque"
  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:produtos
    username: sa
    password: 1
  h2:
    console:
      enabled: true
      path: /h2-console